[package]
name = "nn-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
framework = {path = "framework"}
macroquad = "0.3.25"
