name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependency
        run: sudo apt-get -y install libasound2-dev
      - name: Build
        run: cargo build --verbose

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependency
        run: sudo apt-get -y install libasound2-dev
      - name: Run unit tests
        run: cd framework && cargo test --verbose
